### ISSUE TITLE
Issue with Djoser Imports

### ISSUE THREAD

**Issue by roshanshri09** [linkedweb/auth_system#10]
Hi, I am making it step by step from your yt video. My serializers.py is as below:
    

![image](https://user-images.githubusercontent.com/62870380/155831887-420dcf76-f6f1-4026-adc6-c00f3ac04d55.png)

I have done everything right till now, my settings is updated. I don't understand why importing djoser has an issue. 

![image](https://user-images.githubusercontent.com/62870380/155831915-9c32e7b8-2431-4146-a95a-001cff163890.png)

**Comment by Sreerag-Menon** [comment]
Try to install djoser out of the venv

**Comment by ghost** [comment]
Are you sure djoser is installed? Try installing it again.
